development:
  AIRLINE_SEARCH_HOST: http://localhost:8080
  XML_ROOT : route
  SEARCH_API : /routes/search
  XML_CONTENT_TYPE : application/xml
  JSON_CONTENT_TYPE : application/json

test:
  AIRLINE_SEARCH_HOST: http://localhost:8080
  XML_ROOT : route
  SEARCH_API : /routes/search
  XML_CONTENT_TYPE : application/xml
  JSON_CONTENT_TYPE : application/json

production:
  AIRLINE_SEARCH_HOST : https://morning-everglades-2967.herokuapp.com
  XML_ROOT : route
  SEARCH_API : /routes/search
  XML_CONTENT_TYPE : application/xml
  JSON_CONTENT_TYPE : application/json